### ISSUE TITLE
[Issue/Possible Bug] Admin Dashboard data not displaying

### ISSUE THREAD

**Issue by carlvlewis** [brigadehub/theme-public-c4sf#43]
## Issue Type
Bug

## Issue Description
When logged in as superadmin, the Admin Dashboard with check-in data located at `admin/brigade/dashboard` isn't displaying any values or user data; rather, the page just sits there in perpetuity with the spinning loading circles. 

## Screenshot
![](http://g.recordit.co/i5uvAxF0vG.gif)

## Logs
`2017-05-16T07:12:31.750791+00:00 app[web.1]:     email: 'npalumbo84@gmail.com',
2017-05-16T07:12:31.750791+00:00 app[web.1]:     name: 'Nick Palumbo' } ]
2017-05-16T07:12:31.752356+00:00 app[web.1]: TypeError: Cannot convert undefined or null to object
2017-05-16T07:12:31.752358+00:00 app[web.1]:     at req.mrt.result.req.mrt.result.map (/app/node_modules/brigadehub-core/helpers/mortimer/checkinResource.js:14:23)
2017-05-16T07:12:31.752359+00:00 app[web.1]:     at Array.map (native)
2017-05-16T07:12:31.752360+00:00 app[web.1]:     at /app/node_modules/brigadehub-core/helpers/mortimer/checkinResource.js:12:39
2017-05-16T07:12:31.752360+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-05-16T07:12:31.752361+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-05-16T07:12:31.752362+00:00 app[web.1]:     at req.(anonymous function).query.exec (/app/node_modules/mortimer/lib/Resource.js:524:24)
2017-05-16T07:12:31.752362+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/query.js:2553:18
2017-05-16T07:12:31.752363+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:109:7)
2017-05-16T07:12:31.756059+00:00 app[web.1]: [0mGET /api/checkins?date__gt=1494392725602 [31m500 [0m65.865 ms - -[0m`

**Comment by carlvlewis** [comment]
This issue appears to have resolved itself. Closing.
